//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHardenApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHardenApp.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalyzeTrace_16x {
            get {
                object obj = ResourceManager.GetObject("AnalyzeTrace_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category,Subcategory,GUID,Windows Default,Baseline Recommendation,Stronger Recommendation
        ///Account Logon,Audit Credential Validation,{0CCE923F-69AE-11D9-BED3-505054503030},No | No,Yes | Yes,Yes | Yes
        ///Account Logon,Audit Kerberos Authentication Service,{0CCE9242-69AE-11D9-BED3-505054503030},,,Yes | Yes
        ///Account Logon,Audit Kerberos Service Ticket Operations,{0CCE9240-69AE-11D9-BED3-505054503030},,,Yes | Yes
        ///Account Logon,Audit Other Account Logon Events,{0CCE9241-69AE-11D9-BED3-505054503030},,,Yes | Yes
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auditpolicy_SERVER {
            get {
                return ResourceManager.GetString("auditpolicy_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category,Subcategory,GUID,Windows Default,Baseline Recommendation,Stronger Recommendation
        ///Account Logon,Audit Credential Validation,{0CCE923F-69AE-11D9-BED3-505054503030},No  | No,Yes  | No,Yes  | Yes
        ///Account Logon,Audit Kerberos Authentication Service,{0CCE9242-69AE-11D9-BED3-505054503030},,,Yes  | Yes
        ///Account Logon,Audit Kerberos Service Ticket Operations,{0CCE9240-69AE-11D9-BED3-505054503030},,,Yes  | Yes
        ///Account Logon,Audit Other Account Logon Events,{0CCE9241-69AE-11D9-BED3-505054503030},,,Yes  | Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auditpolicy_WORKSTATION {
            get {
                return ResourceManager.GetString("auditpolicy_WORKSTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_12x_16x {
            get {
                object obj = ResourceManager.GetObject("Close_12x_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Compliant_16x {
            get {
                object obj = ResourceManager.GetObject("Compliant_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConfigurationEditor_16x {
            get {
                object obj = ResourceManager.GetObject("ConfigurationEditor_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExtractConstant_16x {
            get {
                object obj = ResourceManager.GetObject("ExtractConstant_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_grey_16x {
            get {
                object obj = ResourceManager.GetObject("Save_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveStatusBar1_16x {
            get {
                object obj = ResourceManager.GetObject("SaveStatusBar1_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchContract_16x {
            get {
                object obj = ResourceManager.GetObject("SearchContract_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchFolderClosed_16x {
            get {
                object obj = ResourceManager.GetObject("SearchFolderClosed_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
