//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InformationUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [System Access]
        ///MinimumPasswordAge = 1
        ///MaximumPasswordAge = 42
        ///MinimumPasswordLength = 14
        ///PasswordComplexity = 1
        ///PasswordHistorySize = 24
        ///LockoutBadCount = 5
        ///ClearTextPassword = 0
        ///LSAAnonymousNameLookup = 0
        ///EnableAdminAccount = 0
        ///EnableGuestAccount = 0
        ///[Registry Values]
        ///MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin=4,5
        ///MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorUser=4,3
        ///MACHINE\Software\Microsoft\Windows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Basic_Template_Secedit {
            get {
                return ResourceManager.GetString("Basic_Template_Secedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key:HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa
        ///LimitBlankPasswordUse = 1
        ///NoLmHash = 1
        ///SecureBoot = 1
        ///everyoneincludesanonymous = 0
        ///forceguest = 0
        ///restrictanonymous = 1
        ///restrictanonymoussam = 1
        ///LmCompatibilityLevel = 5
        ///RunAsPPL = 1
        ///
        ///Registry key:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters
        ///EnablePlainTextPassword = 0
        ///EnableSecuritySignature = 1
        ///RequireSecuritySignature = 1
        ///
        ///Registry key:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Serv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Registry_Policy {
            get {
                return ResourceManager.GetString("Registry_Policy", resourceCulture);
            }
        }
    }
}
